export { MyCoreModule } from './my-core.module'
export * from './services/logger.service'
export * from './pipes/strings.pipe'
export * from './components/sizer.component'
export * from './components/grafico-svg/grafico-svg.component'
export * from './components/calculator/calculator.component'